apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME_HERE
  labels:
    app: SERVICE_NAME_HERE
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: SERVICE_NAME_HERE
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: SERVICE_NAME_HERE
  labels:
    app: SERVICE_NAME_HERE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME_HERE
  template:
    metadata:
      labels:
        app: SERVICE_NAME_HERE
    spec:
      containers:
      - name: SERVICE_NAME_HERE
        image: IMAGE_TAG_HERE
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.02
            memory: 32Mi
        env:
        - name: ACTIVE_CONFIG
          value: test
        - name: EXTRA_CONFIG
          value: '{"host": "http://mbaas.prod.richinfoai.com"}'
